# Generated by Django 6.0.3 on 2026-04-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
